### ISSUE TITLE
Schedule remote tests

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibo-cloud-backends#24]
Since this package depends not only on libraries, which versions could be pinned, but also on other resources (remote machines) which could change over time, it would be appropriate to periodically test that the implementation is still compliant.

This could be done with a suitable GitHub workflow, applying the `schedule` event:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

**Comment by BrunoLiegiBastonLiegi** [comment]
The tests did run automatically last night, thus I reckon we can close this.
