### ISSUE TITLE
Tests failing in main

### ISSUE THREAD

**Issue by BrunoLiegiBastonLiegi** [qiboteam/qibo-cloud-backends#37]
Some tests are failing in main:
```
FAILED tests/test_backends.py::test_qibo_client_backend[None] - requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
FAILED tests/test_backends.py::test_qibo_client_backend[xxxxxxxxx] - requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```
These seem to be a problem of `qibo-client`.
```
FAILED tests/test_backends.py::test_set_backend[qiskit-client-xxxxxxxxx] - qiskit_ibm_provider.api.exceptions.RequestsApiError: '403 Client Error: Forbidden for url: https://auth.qua...
FAILED tests/test_backends.py::test_qiskit_client_backend_initial_state[True] - qiskit_ibm_provider.api.exceptions.RequestsApiError: '403 Client Error: Forbidden for url: https://auth.qua...
FAILED tests/test_backends.py::test_qiskit_client_backend_initial_state[False] - qiskit_ibm_provider.api.exceptions.RequestsApiError: '403 Client Error: Forbidden for url: https://auth.qua...
```
These are related to being unable to connect to IBMQ I believe. I tried accesing IBMQ directly with my account and received this message:
 "Your IBM Quantum account has been disabled. Learn more: https://ibm.biz/BdfaME."
I had to fill a form and now I am waiting to check if I can get access again, probably the same has to be done for the account used by the tests here.

On top of that I noticed that there is a descrepancy between which names are assigned to the environment variables for the qibo client token. In the tests we called it:

https://github.com/qiboteam/qibo-cloud-backends/blob/6dfbbd24e989d52068815a5b8d04ec8fcc8458d2/tests/test_backends.py#L19

whereas, in the backend:

https://github.com/qiboteam/qibo-cloud-backends/blob/6dfbbd24e989d52068815a5b8d04ec8fcc8458d2/src/qibo_cloud_backends/qibo_client.py#L21

I am not sure which name is assigned to the environment variable in the workflows though. In general, I would suggest to have more generic names:
```
QiboClientBackend --> QIBO_CLIENT_TOKEN
QiskitClientBackend --> QISKIT_CLIENT_TOKEN
```

This is probably a good moment to address #23 and #24 ...

**Comment by scarrazza** [comment]
We have stored: QIBO_CLIENT_TOKEN and IBMQ_TOKEN.
