### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo-cloud-backends#5]
We should include documentation about this package as discussed during the last meeting.

**Comment by scarrazza** [comment]
This repo should be able to render the docs, however we have to introduce the proper CI workflow.

**Comment by alecandido** [comment]
There is the reusable one, just copy the invocation from Qibo :)

**Comment by BrunoLiegiBastonLiegi** [comment]
Sorry for the confusion but it's the first time I deal with this. I've created the workflows in the `.github/workflows` directory, how should I set them up now?

**Comment by alecandido** [comment]
That's it ;)

**Comment by alecandido** [comment]
Actually, since it's not yet the default, @scarrazza might have to set in the settings the GitHub Actions deployment

<img width="707" alt="image" src="https://github.com/qiboteam/qibo-cloud-backends/assets/10830876/213d35e4-b55a-41df-bce0-4e06d24a6bd8">

**Comment by scarrazza** [comment]
I did it during the meeting.

**Comment by alecandido** [comment]
<img width="445" alt="image" src="https://github.com/qiboteam/qibo-cloud-backends/assets/10830876/08dc5476-c914-4bc9-8f97-45cec1d5b9d4">
?

**Comment by scarrazza** [comment]
Yes, it is already set to all actions.

**Comment by alecandido** [comment]
@BrunoLiegiBastonLiegi it was a minor spelling mistake, sorry to have noticed only now...

![image](https://github.com/qiboteam/qibo-cloud-backends/assets/10830876/fc08b814-d613-4ee4-996e-3bb2deae9eb6)

Now it is running, let's check the result and we could close this PR.

**Comment by alecandido** [comment]
Docs deployed!

https://qibo.science/qibo-cloud-backends/stable/

![image](https://github.com/qiboteam/qibo-cloud-backends/assets/10830876/90b61a9a-a4e8-48ae-986a-629d69f9b7d5)
